### ISSUE TITLE
2018 is not compatible with VisualEditor

### ISSUE THREAD

**Issue by MacFan4000** [morags/mediawiki-2018-skin#11]
When attempting to load 2018 with ViisualEditor installed, the skin is broken and there is a message in the console saying that 2018 is not compatible with VisualEditor.

For more details about compatibility see https://www.mediawiki.org/wiki/Extension:VisualEditor/Skin_requirements.

**Comment by morags** [comment]
It should work. What version of VE do you have installed?

**Comment by MacFan4000** [comment]
The version included in the current MediaWiki stable release

**Comment by morags** [comment]
@jdlrobson any idea how to debug this?

**Comment by jdlrobson** [comment]
I think the issue is the missing `#ca-edit` ID listed in https://www.mediawiki.org/wiki/Extension:VisualEditor/Skin_requirements
```
$('#page-tools .uk-icon').attr('id', 'ca-edit')
```
(but do this in PHP)

**Comment by morags** [comment]
You're right, of course. I had a mix-up with _Vector_ and thought I had it working. It didn't work off the bat, but 5693db3725d6b4882a67d27c0fe3586a68374230 should solve it.

**Comment by MacFan4000** [comment]
It works, thanks.
