### ISSUE TITLE
Problem with Mustache syntax on certain pages

### ISSUE THREAD

**Issue by jdlrobson** [morags/mediawiki-2018-skin#9]
On https://skins-demo.wmflabs.org/wiki/Ipsum%20Lorem?useskin=s2018&debug=true I am seeing `( ! ) Notice: Array to string conversion in /vagrant/mediawiki/includes/TemplateParser.php(173) : eval()'d code on line 61`

**Comment by morags** [comment]
Does ba759c6b827389b749c2c766fe379468889795d8 resolve the issue?

**Comment by jdlrobson** [comment]
Nope, seems to be happening because copyrightico can be null here:
```
                    {{#if copyright}}<span>{{{copyrightico}}}{{{copyright}}}</span>{{/if}}
```

My LocalSettings looks like this:
```

$wgRightsUrl = "https://wikimediafoundation.org/";
$wgRightsIcon = "https://www.mediawiki.org/static/images/footer/wikimedia-button.png";
$wgRightsText =  "Foo";

```

**Comment by morags** [comment]
Couldn't replicate, but did have the same error in relation to the watch indicators. 25148e201bf87c0d21df809c6e2a2add8467b220 and 80da80a9318ee52f37ba1b482d592c560bb217dc should solve both.

**Comment by jdlrobson** [comment]
I'll debug a bit more :)

**Comment by jdlrobson** [comment]
Can't replicate any more.
